export const dict : any = {
    english: {
        logo: "GymPro",
        welcome: "Welcome to GymPro",
        subtitle: "Your Ultimate Gym Managment Application",
        getStarted: "Get Started",
        logoAlt: "GymPro goal",
        home: "Home",
        features: "Features",
        contact: "Contact",
        login: "Login",
        logout: "Logout",
        signup: "Sign Up",
        signupFailed: "Signup failed",
        pleaseFillAllFields: "Please fill in all fields",
        passwordLength: "Password must be at least 8 characters long",
        userAlreadyExists: "User already exists!",
        loginFailed: "Login failed",
        checkCredentails: "Please check your credentials.",
        details: "Details",
        success: "Success",
        edit: "Edit",
        delete: "Delete",
        mobileMenu: {
            home: "Home",
            features: "Features",
            contact: "Contact",
        },
        darkModeOn: "Turn on light mode",
        darkModeOff: "Turn on dark mode",
        email: "Email Address",
        password: "Password",
        streams: "Streams",
        continueWithGoogle: "Continue with Google",
        noAccount: "Don't have an account?",
        loginImageAlt: "Illustration of login", 
        emailPlaceholder: "Enter your email",
        passwordPlaceholder: "Enter your password",
        confirmPasswordPlaceholder: "Confirm your password",
        confirmPassword: "Confirm Password",
        passwordsDontMatch: 'Please make sure the passwords match!',
        alreadyHaveAccount: "Already have an account?",
        loading: "Loading",
        loadingText: "We’re getting everything ready for you. It won’t take long!",
        thanks: "Thank you for your patience",
        joinedOn: "Joined on",
        offline: "Offline",
        dashboard: "Dashboard", 
        settings: "Settings",
        notifications: "Notifications",
        noNotification: "No notifications",
        community: "Community",
        help: "Help",
        all: "All",
        yes: "yes",
        no: "No",
        allTopics: "All Topics",
        keys: "Keys",
        generate: "Generate",
        generateConnection: "Generate Connection",
        cancel: "Cancel",
        block: "Block",
        unblock: "Unblock",
        noResults: 'No results found.',
        username: 'Username',
        dateBlocked: 'Date blocked',
        previous: 'Previous',
        next: 'Next',
        language: "Language & Region",
        languageSettings: "Language Settings",
        userProfile: "User Profile",
        privacySettings: "Privacy Settings",
        securitySettings: "Security Settings",
        accountSettings: "Account Settings",
        notificationsSettings: "Notifications Settings",
        appearanceSettings: "Appearance Settings",
        dataBackup: "Data Backup & Restore",
        selectLanguage: "Select Language",
        save: "Save",
        newEmail: "New Email",
        enterNewEmail: "Enter your new email",
        changePassword: "Change Password",
        enterNewPassword: "Enter your new password",
        dataSharing: "Data Sharing",
        twoFactorAuthentication: "Two-Factor Authentication",
        notificationEmail: "Email Notification",
        notificationPush: "Push Notifications",
        manageNotifications: "Email Notifications",
        languages: {
            english: "English",
            french: "French",
            arabic: "Arabic",
            spanish: "Spanish",
        },
        importantFeatures: "Important Features",
        ctaHeading: 'Streamline Your Gym Operations with Ease!',
        ctaDescription: 'Manage your members, track subscriptions, and optimize your gym’s performance with our all-in-one system!',
        ctaButton: 'Get Started Now',
        allRightsReserved: "All rights reserved",
        privacyPolicy: "Privacy Policy",
        termsOfService: "Terms of Service",
        verifyEmail: "Verify Email",
        verificationCode: "Verification Code",
        verificationCodePlaceHolder: "Enter the verification code you received",
        verificationCodeNoReceive: "Did not receive any code?",
        clickHereToResend: "click here to resend",
        checkSpam: "Check your spam folder, or ",
        verificationFailed: "Verification failed, please check again",
        staffCountPlaceholder: 'How many staff members do you have?',
        staffCountLabel: "Number of Staff",
        areYouGymOwner: "Are you a gym owner?",
        submit: "Submit",

    },
}