export const dict : any = {
    english: {
        logo: "GymPro",
        welcome: "Welcome to GymPro",
        subtitle: "Your Ultimate Gym Managment Application",
        getStarted: "Get Started",
        logoAlt: "GymPro goal",
        home: "Home",
        features: "Features",
        contact: "Contact",
        login: "Login",
        logout: "Logout",
        signup: "Sign Up",
        signupFailed: "Signup failed",
        loginFailed: "Login Failed",
        success: "Success",
        edit: "Edit",
        delete: "Delete",
        loadingLogin: "Loading...",
        loadingSignup: "Loading...",
        mobileMenu: {
            home: "Home",
            features: "Features",
            contact: "Contact",
        },
        darkModeOn: "Turn on light mode",
        darkModeOff: "Turn on dark mode",
        email: "Email Address",
        password: "Password",
        streams: "Streams",
        continueWithGoogle: "Continue with Google",
        noAccount: "Don't have an account?",
        loginImageAlt: "Illustration of login", 
        emailPlaceholder: "Enter your email",
        passwordPlaceholder: "Enter your password",
        confirmPasswordPlaceholder: "Confirm your password",
        confirmPassword: "Confirm Password",
        passwordsDontMatch: 'Please make sure the passwords match!',
        alreadyHaveAccount: "Already have an account?",
        loading: "Loading",
        loadingText: "We’re getting everything ready for you. It won’t take long!",
        thanks: "Thanks for your patience",
        SideMenuUsual: "Usual",
        SideMenuRecommended: "Recommended",
        live: "Live",
        liveCapital: "LIVE",
        follow: "Follow", 
        unfollow: "Unfollow", 
        viewers: "Viewers",
        liveChat: "Live Chat",
        chatDisabled: "Chat is Disabled",
        aboutStream: "About the Stream",
        liveStreams: "Live Streams",
        streamTopics: {
            gaming: "Gaming",
            technology: "Technology",
            cooking: "Cooking",
            music: "Music",
            education: "Education",
            sports: "Sports",
            fitness: "Fitness",
            fashion: "Fashion",
            science: "Science",
        },
        joinedOn: "Joined on",
        previousStreams: "Previous Streams",
        currentLiveStream: "Current Live Stream",
        followers: "Followers",
        viewsPerStream: "Views Per Stream",
        youAreLive: "You are live now!",
        offline: "Offline",
        dashboard: "Dashboard", 
        settings: "Settings",
        notifications: "Notifications",
        noNotification: "No notifications",
        community: "Community",
        help: "Help",
        all: "All",
        allTopics: "All Topics",
        streamConnection: "Stream Connection URLs and Keys",
        keys: "Keys",
        stream: "Stream",
        generate: "Generate",
        generateConnection: "Generate Connection",
        serverUrl: "Server URL",
        streamKey: "Stream Key",
        serverUrlPlaceholder: "Your server URL wil appear here",
        streamKeyPlaceholder: "Your stream key wil appear here",
        connectionGenerationWarning: "This action will reset all active streams using the current connection.",
        cancel: "Cancel",
        block: "Block",
        unblock: "Unblock",
        noResults: 'No results found.',
        username: 'Username',
        dateBlocked: 'Date blocked',
        previous: 'Previous',
        next: 'Next',
        language: "Language & Region",
        languageSettings: "Language Settings",
        userProfile: "User Profile",
        privacySettings: "Privacy Settings",
        securitySettings: "Security Settings",
        accountSettings: "Account Settings",
        notificationSettings: "Notification Settings",
        selectLanguage: "Select Language",
        save: "Save",
        newEmail: "New Email",
        enterNewEmail: "Enter your new email",
        changePassword: "Change Password",
        enterNewPassword: "Enter your new password",
        dataSharing: "Data Sharing",
        twoFactorAuthentication: "Two-Factor Authentication",
        notificationEmail: "Email Notification",
        notificationPush: "Push Notifications",
        manageNotifications: "Email Notifications",
        languages: {
            english: "English",
            french: "French",
            arabic: "Arabic",
            spanish: "Spanish",
        },
        importantFeatures: "Important Features",
        ctaHeading: 'Streamline Your Gym Operations with Ease!',
        ctaDescription: 'Manage your members, track subscriptions, and optimize your gym’s performance with our all-in-one system!',
        ctaButton: 'Get Started Now',
        allRightsReserved: "All rights reserved",
        privacyPolicy: "Privacy Policy",
        termsOfService: "Terms of Service",
        
    },
}