export const dict : any = {
    en: {
        logo: "GymPro",
        altLogo: "GymPro Logo",
        welcome: "Welcome to GymPro",
        subtitle: "Your Ultimate Gym Managment Application",
        getStarted: "Get Started",
        logoAlt: "GymPro goal",
        home: "Home",
        features: "Features",
        contact: "Contact",
        login: "Login",
        logout: "Logout",
        signup: "Sign Up",
        signupFailed: "Signup failed",
        pleaseFillAllFields: "Please fill in all fields",
        passwordLength: "Password must be at least 8 characters long",
        userAlreadyExists: "User already exists!",
        loginFailed: "Login failed",
        checkCredentails: "Please check your credentials.",
        details: "Details",
        success: "Success",
        edit: "Edit",
        delete: "Delete",
        mobileMenu: {
            home: "Home",
            features: "Features",
            contact: "Contact",
        },
        darkModeOn: "Turn on light mode",
        darkModeOff: "Turn on dark mode",
        email: "Email Address",
        password: "Password",
        streams: "Streams",
        continueWithGoogle: "Continue with Google",
        noAccount: "Don't have an account?",
        loginImageAlt: "Illustration of login", 
        emailPlaceholder: "Enter your email",
        passwordPlaceholder: "Enter your password",
        confirmPasswordPlaceholder: "Confirm your password",
        confirmPassword: "Confirm Password",
        passwordsDontMatch: 'Please make sure the passwords match!',
        alreadyHaveAccount: "Already have an account?",
        loading: "Loading",
        loadingText: "We’re getting everything ready for you. It won’t take long!",
        thanks: "Thank you for your patience",
        joinedOn: "Joined on",
        offline: "Offline",
        dashboard: "Dashboard", 
        settings: "Settings",
        notifications: "Notifications",
        noNotification: "No notifications",
        community: "Community",
        help: "Help",
        all: "All",
        yes: "yes",
        no: "No",
        allTopics: "All Topics",
        keys: "Keys",
        generate: "Generate",
        generateConnection: "Generate Connection",
        cancel: "Cancel",
        block: "Block",
        unblock: "Unblock",
        noResults: 'No results found.',
        username: 'Username',
        dateBlocked: 'Date blocked',
        previous: 'Previous',
        next: 'Next',
        language: "Language & Region",
        languageSettings: "Language Settings",
        userProfile: "User Profile",
        profile: "Profile",
        subscription: "Subsctiption",
        feedback: "Feedback",
        privacySettings: "Privacy Settings",
        securitySettings: "Security Settings",
        accountSettings: "Account Settings",
        notificationsSettings: "Notifications Settings",
        appearanceSettings: "Appearance Settings",
        dataBackup: "Data Backup & Restore",
        selectLanguage: "Select Language",
        save: "Save",
        newEmail: "New Email",
        enterNewEmail: "Enter your new email",
        changePassword: "Change Password",
        enterNewPassword: "Enter your new password",
        dataSharing: "Data Sharing",
        twoFactorAuthentication: "Two-Factor Authentication",
        notificationEmail: "Email Notification",
        notificationPush: "Push Notifications",
        manageNotifications: "Email Notifications",
        languages: {
            english: "English",
            french: "French",
            arabic: "Arabic",
            spanish: "Spanish",
            italian: "Italian",
            japanese: "Japanese",
        },
        importantFeatures: "Important Features",
        ctaHeading: 'Streamline Your Gym Operations with Ease!',
        ctaDescription: 'Manage your members, track subscriptions, and optimize your gym’s performance with our all-in-one system!',
        ctaButton: 'Get Started Now',
        allRightsReserved: "All rights reserved",
        privacyPolicy: "Privacy Policy",
        termsOfService: "Terms of Service",
        verifyEmail: "Verify Email",
        verificationCode: "Verification Code",
        verificationCodePlaceHolder: "Enter the verification code you received",
        verificationCodeNoReceive: "Did not receive any code?",
        clickHereToResend: "click here to resend",
        checkSpam: "Check your spam folder, or ",
        verificationFailed: "Verification failed, please check again",
        staffCountPlaceholder: 'How many staff members do you have?',
        staffCountLabel: "Number of Staff",
        areYouGymOwner: "Are you a gym owner?",
        submit: "Submit",
        upgradePlan: "Upgrade Plan",
        chatBot: "ChatBot",
        animations: "Animations",
        bgImages: "Background images",
        gymBackgroundAlt: 'Gym Background',
        editProfile: 'Edit Profile',
        yourProfile: 'Your Profile',
        manageProfile: 'Manage your profile settings and preferences',
        name: 'Name',
        membershipType: 'Membership Type',
        saveChanges: 'Save Changes',
        loggingOut: 'Logging out...',
        logOut: 'Log Out',
        profileUpdated: 'Profile updated!',
        totalMembers: 'Total Members',
        monthlyRevenue: 'Monthly Revenue',
        activePlans: 'Active Plans',
        growthRate: 'Growth Rate',
        membershipTrends: 'Membership Trends',
        revenueAnalysis: 'Revenue Analysis',
        dailyActivity: 'Daily Activity',
        subscriptionTypes: 'Subscription Types',
        trendPositive: '+',
        trendNegative: '-',
        assistantGreeting: "Hello! I'm your fitness assistant. How can I help you today?",
        botResponse: "I'm here to help! Let me process your request...",
        botPlaceholder: "Type your message...",
        botTitle: "GymPro Assistant",
        freeTrial: "Free Trial",
        chatbot: "Chatbot",
        switchToLightMode: "Switch to Light Mode",
        switchToDarkMode: "Switch to Dark Mode",
        authentication: "Authentication",
        addMember: "Add Member",
        members: "Members",
        toggleSidebar: "Toggle Sidebar",
        menuHome: "Home",
        menuAuthentication: "Authentication",
        menuAddMember: "Add Member",
        menuMembers: "Members",
        menuDashboard: "Dashboard",
        editMemberTitle: "Edit Member",
        labelName: "Name",
        labelEmail: "Email",
        labelPhone: "Phone",
        labelSubscriptionType: "Subscription Type",
        optionMonthly: "Monthly",
        optionYearly: "Yearly",
        buttonCancel: "Cancel",
        buttonSave: "Save",
        placeholderSubscriptionType: "Subscription Type",
        deleteMemberHeader: "Delete Member",
        deleteMemberConfirmation: "Are you sure you want to delete this member?",
        deleteMemberWarning: "This action cannot be undone.",
        phone: 'Phone',
        joined: 'Joined',
        premium: 'Premium',
        standard: 'Standard',
        active: 'Active',
        inactive: 'Inactive',
        deleteMember: 'Delete Member',
        confirmDeletion: 'Are you sure you want to delete this member?',
        actionUndone: 'This action cannot be undone.',
        joinDate: "Joined on",
        activeStatus: "ACTIVE",
        inactiveStatus: "INACTIVE",
        premiumMembership: "Premium",
        standardMembership: "Standard",
        age: "Age",
        gender: "Gender",
        subscriptionType: "Subscription Type",
        status: "Status",
        lastSubscriptionDate: "Last Sub. Date",
        lastPayment: "Last Payment",
        editButton: "Edit",
        deleteButton: "Delete",
        searchPlaceholder: "Search by name or email...",
        statusPlaceholder: "Select Status",
        membershipPlaceholder: "Select Membership",
        sortPlaceholder: "Sort By",
        resultsSummary: "Showing {count} members",
        noMembers: "No members found matching your criteria",
        selectStatus: 'Select Status',
        selectMembership: 'Select Membership',
        sortBy: 'Sort By',
        showingMembers: 'Showing {count} members',
        noMembersFound: 'No members found matching your criteria',
        statusOptions: [
          { value: 'all', label: 'All Status' },
          { value: 'active', label: 'Active' },
          { value: 'inactive', label: 'Inactive' },
          { value: 'pending', label: 'Pending' },
        ],
        membershipOptions: [
          { value: 'all', label: 'All Memberships' },
          { value: 'basic', label: 'Basic' },
          { value: 'premium', label: 'Premium' },
          { value: 'vip', label: 'VIP' },
        ],
        sortOptions: [
          { value: 'name', label: 'Sort by Name' },
          { value: 'joinDate', label: 'Sort by Join Date' },
        ],
        retake: "Retake",
        use: "Use",
        chooseYourPlan: "Choose Your Plan",
        popular: "Popular",
        selected: "Selected",
        selectPlan: "Select Plan",
        confirmSelection: "Confirm Selection",
        plansFeatures: [
          "Up to 1,000 messages",
          "Basic support",
          "1 team member",
          "Up to 10,000 messages",
          "Priority support",
          "5 team members",
          "Advanced analytics",
          "Unlimited messages",
          "24/7 support",
          "Unlimited team members",
          "Custom features",
          "API access"
        ],
        plans: [
          { name: "Starter", price: "$9/mo" },
          { name: "Pro", price: "$29/mo" },
          { name: "Enterprise", price: "$99/mo" }
        ],
        namePlaceholder: "Enter name",
        agePlaceholder: "Enter age",
        genderPlaceholder: "Gender",
        phonePlaceholder: "Enter phone number",
        subscriptionTypePlaceholder: "Subscription Type",
        captureImage: "Capture Image",
        turnOffCamera: "Turn Off Camera",
        turnOnCamera: "Turn On Camera",
        captureImageShortcut: "Or press Ctrl+x to capture image",
        nameRequired: "Name is required",
        validAge: "Enter a valid age",
        genderRequired: "Gender is required",
        validEmail: "Enter a valid email",
        phoneRequired: "Phone number is required",
        subscriptionRequired: "Subscription type is required",
        processing: "Processing...",
        successMessage: "Member added successfully!",
        male: "Male",
        female: "Female",
        monthly: "Monthly", 
        yearly: "Yearly",
        recognitionResults: 'Recognition Results',
        resultMessagePlaceholder: 'Results will appear here after capturing an image.',
        cameraError: 'Error accessing camera. Please check permissions.',
        shortcutInstruction: 'Or press Ctrl+x to capture image',
        newMembers: "New Members",
        activeMembers: 'Active Members',
        newMembersToday: 'New Members Today',
        revenueToday: 'Revenue Today',
        checkIns: 'Check-ins',
    },
    fr: {
      logo: "GymPro",
      altLogo: "Logo GymPro",
      welcome: "Bienvenue à GymPro",
      subtitle: "Votre application de gestion de gym ultime",
      getStarted: "Commencer",
      logoAlt: "Objectif GymPro",
      home: "Accueil",
      features: "Fonctionnalités",
      contact: "Contact",
      login: "Connexion",
      logout: "Déconnexion",
      signup: "S'inscrire",
      signupFailed: "Échec de l'inscription",
      pleaseFillAllFields: "Veuillez remplir tous les champs",
      passwordLength: "Le mot de passe doit comporter au moins 8 caractères",
      userAlreadyExists: "L'utilisateur existe déjà !",
      loginFailed: "Échec de la connexion",
      checkCredentails: "Veuillez vérifier vos identifiants.",
      details: "Détails",
      success: "Succès",
      edit: "Modifier",
      delete: "Supprimer",
      mobileMenu: {
          home: "Accueil",
          features: "Fonctionnalités",
          contact: "Contact",
      },
      darkModeOn: "Activer le mode clair",
      darkModeOff: "Activer le mode sombre",
      email: "Adresse e-mail",
      password: "Mot de passe",
      streams: "Flux",
      continueWithGoogle: "Continuer avec Google",
      noAccount: "Vous n'avez pas de compte ?",
      loginImageAlt: "Illustration de connexion", 
      emailPlaceholder: "Entrez votre e-mail",
      passwordPlaceholder: "Entrez votre mot de passe",
      confirmPasswordPlaceholder: "Confirmer votre mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      passwordsDontMatch: 'Veuillez vous assurer que les mots de passe correspondent !',
      alreadyHaveAccount: "Vous avez déjà un compte ?",
      loading: "Chargement",
      loadingText: "Nous préparons tout pour vous. Cela ne prendra pas longtemps !",
      thanks: "Merci pour votre patience",
      joinedOn: "Inscrit le",
      offline: "Hors ligne",
      dashboard: "Tableau de bord", 
      settings: "Paramètres",
      notifications: "Notifications",
      noNotification: "Aucune notification",
      community: "Communauté",
      help: "Aide",
      all: "Tous",
      yes: "oui",
      no: "Non",
      allTopics: "Tous les sujets",
      keys: "Clés",
      generate: "Générer",
      generateConnection: "Générer la connexion",
      cancel: "Annuler",
      block: "Bloquer",
      unblock: "Débloquer",
      noResults: 'Aucun résultat trouvé.',
      username: "Nom d'utilisateur",
      dateBlocked: 'Date de blocage',
      previous: 'Précédent',
      next: 'Suivant',
      language: "Langue & Région",
      languageSettings: "Paramètres de langue",
      userProfile: "Profil de l'utilisateur",
      profile: "Profil",
      subscription: "Abonnement",
      feedback: "Retour d'information",
      privacySettings: "Paramètres de confidentialité",
      securitySettings: "Paramètres de sécurité",
      accountSettings: "Paramètres du compte",
      notificationsSettings: "Paramètres des notifications",
      appearanceSettings: "Paramètres d'apparence",
      dataBackup: "Sauvegarde et restauration des données",
      selectLanguage: "Sélectionner la langue",
      save: "Sauvegarder",
      newEmail: "Nouvelle adresse e-mail",
      enterNewEmail: "Entrez votre nouvelle adresse e-mail",
      changePassword: "Changer le mot de passe",
      enterNewPassword: "Entrez votre nouveau mot de passe",
      dataSharing: "Partage des données",
      twoFactorAuthentication: "Authentification à deux facteurs",
      notificationEmail: "Notification par e-mail",
      notificationPush: "Notifications push",
      manageNotifications: "Gérer les notifications par e-mail",
      languages: {
          english: "Anglais",
          french: "Français",
          arabic: "Arabe",
          spanish: "Espagnol",
          italian: "Italien",
          japanese: "Japonais",
      },
      importantFeatures: "Fonctionnalités importantes",
      ctaHeading: 'Simplifiez la gestion de votre gym avec aisance !',
      ctaDescription: 'Gérez vos membres, suivez les abonnements et optimisez les performances de votre gym avec notre système tout-en-un !',
      ctaButton: 'Commencez maintenant',
      allRightsReserved: "Tous droits réservés",
      privacyPolicy: "Politique de confidentialité",
      termsOfService: "Conditions d'utilisation",
      verifyEmail: "Vérifier l'e-mail",
      verificationCode: "Code de vérification",
      verificationCodePlaceHolder: "Entrez le code de vérification que vous avez reçu",
      verificationCodeNoReceive: "Vous n'avez pas reçu de code ?",
      clickHereToResend: "cliquez ici pour renvoyer",
      checkSpam: "Vérifiez votre dossier spam, ou ",
      verificationFailed: "Échec de la vérification, veuillez vérifier à nouveau",
      staffCountPlaceholder: 'Combien de membres du personnel avez-vous ?',
      staffCountLabel: "Nombre de membres du personnel",
      areYouGymOwner: "Êtes-vous propriétaire d'une salle de sport ?",
      submit: "Soumettre",
      upgradePlan: "Mettre à niveau le plan",
      chatBot: "ChatBot",
      animations: "Animations",
      bgImages: "Images de fond",
      gymBackgroundAlt: 'Fond de gym',
      editProfile: 'Modifier le profil',
      yourProfile: 'Votre profil',
      manageProfile: 'Gérez vos paramètres et préférences de profil',
      name: 'Nom',
      membershipType: 'Type d\'abonnement',
      saveChanges: 'Sauvegarder les modifications',
      loggingOut: 'Déconnexion...',
      logOut: 'Déconnexion',
      profileUpdated: 'Profil mis à jour !',
      totalMembers: 'Membres totaux',
      monthlyRevenue: 'Revenu mensuel',
      activePlans: 'Plans actifs',
      growthRate: 'Taux de croissance',
      membershipTrends: 'Tendances d\'adhésion',
      revenueAnalysis: 'Analyse des revenus',
      dailyActivity: 'Activité quotidienne',
      subscriptionTypes: 'Types d\'abonnement',
      trendPositive: '+',
      trendNegative: '-',
      assistantGreeting: "Bonjour ! Je suis votre assistant fitness. Comment puis-je vous aider aujourd'hui ?",
      botResponse: "Je suis ici pour vous aider ! Laissez-moi traiter votre demande...",
      botPlaceholder: "Tapez votre message...",
      botTitle: "Assistant GymPro",
      freeTrial: "Essai gratuit",
      chatbot: "Chatbot",
      switchToLightMode: "Passer au mode clair",
      switchToDarkMode: "Passer au mode sombre",
      authentication: "Authentification",
      addMember: "Ajouter un membre",
      members: "Membres",
      toggleSidebar: "Basculer la barre latérale",
      menuHome: "Accueil",
      menuAuthentication: "Authentification",
      menuAddMember: "Ajouter un membre",
      menuMembers: "Membres",
      menuDashboard: "Tableau de bord",
      editMemberTitle: "Modifier le membre",
      labelName: "Nom",
      labelEmail: "E-mail",
      labelPhone: "Téléphone",
      labelSubscriptionType: "Type d'abonnement",
      optionMonthly: "Mensuel",
      optionYearly: "Annuel",
      buttonCancel: "Annuler",
      buttonSave: "Sauvegarder",
      placeholderSubscriptionType: "Type d'abonnement",
      deleteMemberHeader: "Supprimer le membre",
      deleteMemberConfirmation: "Êtes-vous sûr de vouloir supprimer ce membre ?",
      deleteMemberWarning: "Cette action ne peut pas être annulée.",
      phone: 'Téléphone',
      joined: 'Inscrit',
      premium: 'Premium',
      standard: 'Standard',
      active: 'Actif',
      inactive: 'Inactif',
      deleteMember: 'Supprimer le membre',
      confirmDeletion: 'Êtes-vous sûr de vouloir supprimer ce membre ?',
      actionUndone: 'Cette action ne peut pas être annulée.',
      joinDate: "Inscrit le",
      activeStatus: "ACTIF",
      inactiveStatus: "INACTIF",
      premiumMembership: "Premium",
      standardMembership: "Standard",
      age: "Âge",
      gender: "Genre",
      subscriptionType: "Type d'abonnement",
      status: "Statut",
      lastSubscriptionDate: "Date de dernier abonnement",
      lastPayment: "Dernier paiement",
      editButton: "Modifier",
      deleteButton: "Supprimer",
      searchPlaceholder: "Rechercher par nom ou e-mail...",
      statusPlaceholder: "Sélectionner le statut",
      membershipPlaceholder: "Sélectionner l'abonnement",
      sortPlaceholder: "Trier par",
      resultsSummary: "Affichage de {count} membres",
      noMembers: "Aucun membre correspondant à vos critères",
      selectStatus: 'Sélectionner le statut',
      selectMembership: 'Sélectionner l\'abonnement',
      sortBy: 'Trier par',
      showingMembers: 'Affichage de {count} membres',
      noMembersFound: 'Aucun membre correspondant à vos critères',
      statusOptions: [
        { value: 'all', label: 'Tous' },
        { value: 'active', label: 'Actifs' },
        { value: 'inactive', label: 'Inactifs' },
      ],
      membershipOptions: [
        { value: 'all', label: 'Tous' },
        { value: 'premium', label: 'Premium' },
        { value: 'standard', label: 'Standard' },
      ],
      sortOptions: [
        { value: 'name', label: 'Nom' },
        { value: 'joinDate', label: 'Date d\'inscription' },
        { value: 'lastPayment', label: 'Dernier paiement' },
      ],
      detailsPlaceholder: "Détails",
      addMemberPlaceholder: "Ajouter un membre",
      memberData: "Données du membre",
      addNewMember: "Ajouter un nouveau membre",
      newMemberTitle: "Nouveau membre",
      memberSaved: "Membre enregistré avec succès !",
      memberDeleted: "Membre supprimé avec succès !",
      invalidData: "Données invalides, veuillez réessayer.",
      user: "Utilisateur",
      pleaseWait: "Veuillez patienter...",
      memberAlreadyExists: "Le membre existe déjà !",
      memberSuccessfullyAdded: "Membre ajouté avec succès !",
      welcomeBack: "Content de vous revoir !",
      profileImage: "Image de profil",
      chooseFile: "Choisir un fichier",
      uploadImage: "Télécharger une image",
      changeProfilePicture: "Changer l'image de profil",
      filterMembers: "Filtrer les membres",
      filterBy: "Filtrer par",
      filterByGender: "Filtrer par sexe",
      filterByExpiredSubscription: "Filtrer par abonnement expiré",
      allMembers: "Tous les membres",
      memberName: "Nom du membre",
      clearFilters: "Effacer les filtres",
      searchMembers: "Rechercher des membres",
      searchBy: "Rechercher par",
      memberProfile: "Profil du membre",
      profilePicture: "Image de profil",
      upload: "Télécharger",
      cancelUpload: "Annuler le téléchargement",
      uploadSuccess: "Téléchargement réussi !",
      uploadFailed: "Échec du téléchargement, veuillez réessayer.",
      chooseSubscriptionType: "Choisir le type d'abonnement",
      subscriptionPlan: "Plan d'abonnement",
      membershipPlan: "Plan d'adhésion",
      upgradeSuccess: "Mise à niveau réussie !",
      upgradeFailed: "Échec de la mise à niveau, veuillez réessayer.",
      addMemberSuccess: "Membre ajouté avec succès !",
      editMemberSuccess: "Membre modifié avec succès !",
      deleteMemberSuccess: "Membre supprimé avec succès !",
      cancelSuccess: "Annulation réussie !",
      cancelFailed: "Échec de l'annulation, veuillez réessayer.",
      completeRegistration: "Terminer l'enregistrement",
      completeProfile: "Compléter le profil",
      backToHome: "Retour à l'accueil",
      fitnessTips: "Conseils de fitness",
      workoutPlans: "Plans d'entraînement",
      nutritionGuides: "Guides nutritionnels",
      memberProfileUpdated: "Profil du membre mis à jour !",
      chooseAction: "Choisir une action",
      createMember: "Créer un membre",
      viewMember: "Voir le membre",
      updateMember: "Mettre à jour le membre",
      removeMember: "Retirer le membre",
      loadMore: "Charger plus",
      memberSince: "Membre depuis",
      sessionTimeout: "Votre session a expiré. Veuillez vous reconnecter.",
      updateSuccess: "Mise à jour réussie !",
      generalSettings: "Paramètres généraux",
      helpCenter: "Centre d'aide",
      userManual: "Manuel de l'utilisateur",
      feedbackTitle: "Vos retours",
      feedbackMessage: "Nous apprécions vos commentaires pour améliorer notre application.",
      sendFeedback: "Envoyer vos retours",
      feedbackSent: "Retour envoyé avec succès !",
      feedbackFailed: "Échec de l'envoi du retour, veuillez réessayer.",
      submitFeedback: "Soumettre vos retours",
      loginToContinue: "Connectez-vous pour continuer",
      aboutUs: "À propos de nous",
      contactUs: "Contactez-nous",
      findUs: "Trouvez-nous",
      communityGuidelines: "Directives de la communauté",
      reportIssue: "Signaler un problème",
      followUs: "Suivez-nous",
      followUsOn: "Suivez-nous sur",
      privacyNotice: "Avis de confidentialité",
      termsAndConditions: "Conditions générales",
      termsAgreement: "En utilisant notre application, vous acceptez nos conditions.",
      unsubscribe: "Se désinscrire",
      emailAddress: "Adresse e-mail",
      requestSent: "Demande envoyée !",
      requestFailed: "Échec de la demande, veuillez réessayer.",
      verificationRequired: "Vérification requise",
      verificationEmailSent: "E-mail de vérification envoyé.",
      verificationEmailNotReceived: "Vous n'avez pas reçu d'e-mail de vérification ?",
      resendVerificationEmail: "Renvoyer l'e-mail de vérification",
      resetPassword: "Réinitialiser le mot de passe",
      resetLinkSent: "Lien de réinitialisation envoyé !",
      resetFailed: "Échec de la réinitialisation, veuillez réessayer.",
      passwordResetSuccess: "Réinitialisation réussie !",
      passwordResetFailed: "Échec de la réinitialisation du mot de passe, veuillez réessayer.",
      welcomeMessage: "Bienvenue dans votre tableau de bord !",
      recentActivities: "Activités récentes",
      currentMembers: "Membres actuels",
      analytics: "Analytique",
      analyticsOverview: "Aperçu des analyses",
      revenueOverview: "Aperçu des revenus",
      growthOverview: "Aperçu de la croissance",
      gymOverview: "Aperçu du gymnase",
      membershipStatistics: "Statistiques d'adhésion",
      totalRevenue: "Revenu total",
      revenueChart: "Graphique des revenus",
      memberStatistics: "Statistiques des membres",
      membershipGrowth: "Croissance de l'adhésion",
      activityOverview: "Aperçu de l'activité",
      gymPerformance: "Performance du gymnase",
      recentMembers: "Membres récents",
      review: "Critique",
      averageSessionTime: "Temps moyen de session",
      topClasses: "Meilleures classes",
      contactSupport: "Contacter le support",
      supportAvailable: "Support disponible 24h/24 et 7j/7",
      customerSupport: "Support client",
      gymNews: "Actualités du gymnase",
      subscribeToNewsletter: "S'abonner à la newsletter",
      newsletterSubscription: "Abonnement à la newsletter",
      subscribe: "S'abonner",
      unsubscribeSuccess: "Désinscription réussie !",
      unsubscribeFailed: "Échec de la désinscription, veuillez réessayer.",
      newsletterSent: "Newsletter envoyée !",
      newsletterFailed: "Échec de l'envoi de la newsletter, veuillez réessayer.",
      planOverview: "Aperçu du plan",
      paymentHistory: "Historique des paiements",
      paymentDetails: "Détails du paiement",
      billingInformation: "Informations de facturation",
      updateBillingInfo: "Mettre à jour les informations de facturation",
      paymentMethod: "Méthode de paiement",
      selectPaymentMethod: "Sélectionner la méthode de paiement",
      savePaymentMethod: "Sauvegarder la méthode de paiement",
      paymentSuccessful: "Paiement réussi !",
      paymentFailed: "Échec du paiement, veuillez réessayer.",
      planType: "Type de plan",
      currentPlan: "Plan actuel",
      upgradeOptions: "Options de mise à niveau",
      upgradeToPremium: "Mettre à niveau vers Premium",
      upgradeToStandard: "Mettre à niveau vers Standard",
      confirmUpgrade: "Confirmer la mise à niveau",
      upgradeSuccessMessage: "Vous avez été mis à niveau avec succès !",
      upgradeFailedMessage: "Échec de la mise à niveau, veuillez réessayer.",
      welcomeBackMessage: "Content de vous revoir !",
      thankYou: "Merci !",
      lookingForward: "Nous avons hâte de vous voir bientôt !",
      happyToAssist: "Nous sommes heureux de vous aider.",
      gymCommunity: "Communauté de gym",
      joinTheCommunity: "Rejoignez notre communauté de gymnases",
      communityEvents: "Événements communautaires",
      trainingPrograms: "Programmes d'entraînement",
      fitnessChallenges: "Défis de fitness",
      fitnessGoals: "Objectifs de fitness",
      planYourGoals: "Planifiez vos objectifs de fitness",
      motivation: "Motivation",
      workoutTips: "Conseils d'entraînement",
      mealPlans: "Plans de repas",
      fitnessArticles: "Articles de fitness",
      gymUpdates: "Mises à jour du gymnase",
      healthTips: "Conseils de santé",
      wellnessResources: "Ressources de bien-être",
      schedule: "Horaire",
      findClasses: "Trouvez des cours",
      classSchedule: "Horaires des cours",
      bookClass: "Réserver un cours",
      classDetails: "Détails du cours",
      instructor: "Instructeur",
      classCapacity: "Capacité du cours",
      upcomingEvents: "Événements à venir",

    },

    
}
